FILES = ProducerConsumer.java Consumer.java Producer.java Buffer.java
all:
	javac -g $(FILES)
clean:
	rm *.class
run:
	java ProducerConsumer
package:
	zip -r Noah-Larchick-HW4.zip ProducerConsumer.java Consumer.java Producer.java Buffer.java Makefile README.txt